---
title: "QQM Mobility"
  knit: (function(input_file, encoding) {
    out_dir <- 'docs';
    rmarkdown::render(input_file,
      encoding=encoding,
      output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Rowan Carew"
date: "2023-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load libraries
library(dplyr)
library(ggplot2)
library(naniar)
library(tidyverse)
library(janitor)
library(skimr)
library(psych)
library(ggdist)
library(car)
library(correlation)
library(scales)
library(gtsummary)
library(quantreg)
```

```{r}
#load("database_PT_final.Rda")
#NB - the data is called "database"

#database_choices=read.csv("finaldata.csv",header=TRUE)

#database<-inner_join(database_choices, database, by ='RID')
```



```{r}
database <-
  database %>%
  mutate(sex_front = as.factor(sex_front),
         p_bundesland_front = as.factor(p_bundesland_front),
         p_educ_front = as.factor(p_educ_front),
         age_front = as.integer(age_front),
         m_known = as.factor(m_known),
         DRT_knowledge = as.factor(DRT_knowledge),
         p_place_inhab = as.factor(p_place_inhab)
         )

glimpse(database)
```

```{r}
database_rural <- subset(database, p_place_inhab %in% c(1,2))

database_nonrural <- subset(database, p_place_inhab %in% c(3,4,5))

```


```{r}
table(database_rural$sex_front)

database_rural_boomer_filtered <- database_rural %>%
  filter(DURATION < quantile(DURATION, 0.95))

ggplot(data = database_rural_boomer_filtered) + 
  geom_point(mapping = aes(x = age_front, y = DURATION)) +
  geom_smooth(mapping = aes(x = age_front, y = DURATION)) +
ggtitle ("Boomerism and being shit at surveys")
```

```{r}
database_rural_boomer_filtered %>%
  select(age_front, DURATION) %>%
  correlation(method = "spearman")
```
##Comparing rural and nonrural kilometrage

#Rural regions
```{r}
# Creating four separate databases from the rural database containing the kilometrage variable without missing data
database_kilometres_rural_1 <- subset(database_rural, kilometrage_per_car_1 %in% c(1,2,3,4,5))
database_kilometres_rural_2 <- subset(database_rural, kilometrage_per_car_2 %in% c(1,2,3,4,5))
database_kilometres_rural_3 <- subset(database_rural, kilometrage_per_car_3 %in% c(1,2,3,4,5))
database_kilometres_rural_4 <- subset(database_rural, kilometrage_per_car_4 %in% c(1,2,3,4,5))

# Creating new data frame "kilometres" used to label the x axis of the plots
kilometres <- c("1" = "0 or up to 1,000 km", "2"="1,000 to 5,000 km", "3" = "5,000 to 10,000 km", "4" = "10,000 to 15,000 km", "5" ="15,000 to 25,000 km", "6" = "over 25,000 km")

# Constructing databases to rename the x axis
database_kilometres_rural_1 <- database_kilometres_rural_1 %>%
    mutate(kilometrage_per_car_1 = factor(kilometrage_per_car_1, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

database_kilometres_rural_2 <- database_kilometres_rural_2 %>%
    mutate(kilometrage_per_car_2 = factor(kilometrage_per_car_2, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

database_kilometres_rural_3 <- database_kilometres_rural_3 %>%
    mutate(kilometrage_per_car_3 = factor(kilometrage_per_car_3, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

database_kilometres_rural_4 <- database_kilometres_rural_4 %>%
    mutate(kilometrage_per_car_4 = factor(kilometrage_per_car_4, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

# Plotting Total car kilometrage
ggplot(database_kilometres_rural_1, aes(x = kilometrage_per_car_1)) +
  geom_bar(position = "dodge", fill = "orange") +
  labs(title = "Total kilometrage in rural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Plotting Car 1
ggplot(database_kilometres_rural_2, aes(x = kilometrage_per_car_2)) +
  geom_bar(position = "dodge", fill = "orange") +
  labs(title = "Most used car kilometrage in rural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Plotting Car 2
ggplot(database_kilometres_rural_3, aes(x = kilometrage_per_car_3)) +
  geom_bar(position = "dodge", fill = "orange") +
  labs(title = "Car 2 kilometrage in rural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# Plotting Car 3
ggplot(database_kilometres_rural_4, aes(x = kilometrage_per_car_4)) +
  geom_bar(position = "dodge", fill = "orange") +
  labs(title = "Car 3 kilometrage in rural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
#Nonrural regions
```{r}
database_kilometres_nonrural_1 <- subset(database_nonrural, kilometrage_per_car_1 %in% c(1,2,3,4,5))
database_kilometres_nonrural_2 <- subset(database_nonrural, kilometrage_per_car_2 %in% c(1,2,3,4,5))
database_kilometres_nonrural_3 <- subset(database_nonrural, kilometrage_per_car_3 %in% c(1,2,3,4,5))
database_kilometres_nonrural_4 <- subset(database_nonrural, kilometrage_per_car_4 %in% c(1,2,3,4,5))


database_kilometres_nonrural_1 <- database_kilometres_nonrural_1 %>%
    mutate(kilometrage_per_car_1 = factor(kilometrage_per_car_1, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

database_kilometres_nonrural_2 <- database_kilometres_nonrural_2 %>%
    mutate(kilometrage_per_car_2 = factor(kilometrage_per_car_2, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

database_kilometres_nonrural_3 <- database_kilometres_nonrural_3 %>%
    mutate(kilometrage_per_car_3 = factor(kilometrage_per_car_3, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

database_kilometres_nonrural_4 <- database_kilometres_nonrural_4 %>%
    mutate(kilometrage_per_car_4 = factor(kilometrage_per_car_4, 
                                          levels = as.character(1:6), 
                                          labels = kilometres))

ggplot(database_kilometres_nonrural_1, aes(x = kilometrage_per_car_1)) +
  geom_bar(position = "dodge", fill = "slateblue") +
  labs(title = "Total kilometrage in nonrural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplot(database_kilometres_nonrural_2, aes(x = kilometrage_per_car_2)) +
  geom_bar(position = "dodge", fill = "slateblue") +
  labs(title = "Most used car kilometrage in nonrural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplot(database_kilometres_nonrural_3, aes(x = kilometrage_per_car_3)) +
  geom_bar(position = "dodge", fill = "slateblue") +
  labs(title = "Car 2 kilometrage in nonrural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplot(database_kilometres_nonrural_4, aes(x = kilometrage_per_car_4)) +
  geom_bar(position = "dodge", fill = "slateblue") +
  labs(title = "Car 3 kilometrage in nonrural regions",
       x = "Kilometrage per year",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
#Rural car 2

```{r}
#I want to create a clustered bar chart showing the different frequencies of whether people own a car or not in different Austrian states.

#First, I will rename the variables. This will make the graph more readable.
library(dplyr)

#Create a copy of the database to play with.
database_test <- database_rural

#Rename the variables. Start with value mapping (vm)
database_test__p_bundesland_vm <- c("1" = "Burgenland", "2" = "Kärnten", "3" = "Niederösterreich", "4" = "Oberösterreich", "5" = "Salzburg", "6" = "Steiermark", "7" = "Tirol", "8" = "Vorarlberg", "9" = "Wien", "10" = "Not Austria")

database_test_p_mtools_1_vm <- c("1" = "No", "2" = "Yes")

database_test <- database_test %>%
  mutate(p_bundesland_front = factor(p_bundesland_front, levels = as.character(1:10), labels = database_test__p_bundesland_vm))

database_test <- database_test %>%
  mutate(p_mtools_1 = factor(p_mtools_1, levels = as.character(1:2), labels = database_test_p_mtools_1_vm))



# Here I create a clustered bar chart.

library(ggplot2)
ggplot(database_test, aes(x = p_bundesland_front, fill = p_mtools_1)) +
  geom_bar(position = "dodge") +
  labs(title = "Do you have a car?",
       x = "p_bundesland_front",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


```{r}
database_inhab_complete <- subset(database, p_place_inhab %in% c(1,2,3,4,5))

inhabitants <- c("1" = "up to 1,000", "2"="1,000 to 5,000", "3" = "5,000 to 50,000", "4" = "50,000 to 100,000", "5" ="more than 100.000")

database_inhab_complete <- database_inhab_complete %>%
    mutate(p_place_inhab = factor(p_place_inhab, 
                                          levels = as.character(1:5), 
                                          labels = inhabitants))

ggplot(database_inhab_complete, aes(x = n_o_v_hh, fill = p_place_inhab)) +
  geom_bar(position = "dodge") +
  labs(title = "How many cars in which sized town?",
       x = "Number of cars",
       y = "Frequency") 
```
```{r}
#should the y variable be continous
tb1 <- glm(p_place_inhab~n_o_v_hh + p_central_nonwien + p_mob_time + p_mob_rural + kilometrage_per_car_2,data=database)
tbl_regression(tb1)
plot(tb1)
```

```{r}
tb2 <- rq(age_front~p_place_inhab + p_central_nonwien + p_mob_time + p_mob_rural + kilometrage_per_car_2,data=database, tau= seq(0.1, 0.9, by = 0.1))
quantreg.plot <- summary(tb2)
plot(quantreg.plot)
```


```{r}
database %>%
  group_by(buy_actually_e1) %>%
  count(sort = TRUE)

database %>%
  group_by(buy_actually_e2) %>%
  count(sort = TRUE)

database %>%
  group_by(buy_actually_e3) %>%
  count(sort = TRUE)

database %>%
  group_by(buy_actually_e4) %>%
  count(sort = TRUE)

database %>%
  group_by(buy_actually_e5) %>%
  count(sort = TRUE)
```

```{r}
#Nested Logit
library(mlogit)

database_cleaned <- na.omit(database)

database_dummy_e1 <- database_cleaned %>%
  mutate(dummy_e1 = as.integer(buy_actually_e1 == 6))
print(database_dummy_e1$dummy_e1)

mlogit_model <- mlogit(dummy_e1 ~ NO_against_personal_1 +
                       NO_against_personal_2 + 
                      NO_against_personal_3,
                       data = database_dummy_e1,
                       reflevel = "baseline_choice")
```

```{r}
library(correlation)
library(ggcorrplot)


database %>%
  mutate(p_mob_time = as.factor(p_mob_time),
         p_mob_rural = as.factor(p_mob_rural),
         p_central_nonwien = as.factor(p_central_nonwien)
         )   %>%

  select(p_mob_time, p_mob_rural, p_central_nonwien) %>%

  correlation() 
```
##Pre choice experiment correlation matrix
```{r}
library(correlation)
library(ggcorrplot)

#Car Ownership  
database<-filter(database,p_mtools_1==2)
#Rural
#database<-filter(database,p_place_inhab<3)

database %>%
  mutate(sex_front = as.numeric(sex_front),
         p_bundesland_front = as.numeric(p_bundesland_front),
         p_educ_front = as.numeric(p_educ_front),
         age_front = as.numeric(age_front),
         m_known = as.numeric(m_known),
         DRT_knowledge = as.numeric(DRT_knowledge),
         p_place_inhab = as.numeric(p_place_inhab),
         p_central_nonwien = as.numeric(p_central_nonwien),
         p_mob_ptintensity = as.numeric(p_mob_ptintensity),
         p_mob_time = as.numeric(p_mob_time),
         p_mob_rural = as.numeric(p_mob_rural),
         n_o_v_hh = as.numeric(n_o_v_hh),
         kilometrage_per_car_1 = as.numeric(kilometrage_per_car_1),
         kilometrage_per_car_2 = as.numeric(kilometrage_per_car_2),
         p_mtools_1 = as.numeric(p_mtools_1)
         )   %>%

  select(sex_front,
         p_bundesland_front,
         p_educ_front,
         age_front,
         m_known,
         DRT_knowledge,
         p_place_inhab,
         p_central_nonwien,
         p_mob_ptintensity,
         p_mob_time,
         p_mob_rural,
         n_o_v_hh,
         kilometrage_per_car_1,
         kilometrage_per_car_2,
         p_mtools_1) %>%

  cor() %>% 
  ggcorrplot()
```

